# Generated by Django 4.2.13 on 2025-04-08 12:33

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0037_is_archive_for_history'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
                ('cte_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='test',
            index=django.contrib.postgres.indexes.BTreeIndex(condition=models.Q(('is_deleted', False)), fields=['plan', 'id'], name='idx_test_plan_id_is_deleted'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['test', 'created_at'], name='idx_result_test_id_created_at'),
        ),
    ]
