# Generated by Django 4.2.13 on 2025-04-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0038_alter_test_managers_alter_testresult_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testplan',
            options={'default_related_name': 'test_plans', 'ordering': ['id']},
        ),
    ]
