# Generated by Django 4.2.13 on 2025-04-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0039_alter_testplan_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
            ],
        ),
    ]
