# Generated by Django 4.2.13 on 2025-02-04 15:37

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0021_testsuite_attributes'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='testcase',
            name='cases_count_decrement_statistics_on_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='testcase',
            name='cases_count_increment_statistics_on_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='testcase',
            name='cases_count_decrement_statistics_on_delete',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='testsuite',
            name='suites_count_decrement_statistics_on_delete',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_decrement_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NEW."is_deleted" AND NOT OLD."is_deleted" AND NOT OLD."is_archive") OR (NEW."is_archive" AND NOT OLD."is_archive" AND NOT OLD."is_deleted"))', func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count - 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='c74e25202809736015185b82a006528ae5238268', operation='UPDATE', pgid='pgtrigger_cases_count_decrement_statistics_on_update_ed1bc', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_increment_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NOT NEW."is_deleted" AND OLD."is_deleted" AND NOT NEW."is_archive") OR (NOT NEW."is_archive" AND OLD."is_archive" AND NOT NEW."is_deleted"))', func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count + 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='c39010d21daae8e5728ec356f17c170ddfd5492a', operation='UPDATE', pgid='pgtrigger_cases_count_increment_statistics_on_update_c529f', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_decrement_statistics_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NOT OLD."is_archive" AND NOT OLD."is_deleted")', func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count - 1 \n            WHERE project_id = OLD.project_id;\n            RETURN OLD;\n            ', hash='9e5674f67db9cdaa748348dc111a5f2f5a28d63f', operation='DELETE', pgid='pgtrigger_cases_count_decrement_statistics_on_delete_9e1e1', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testsuite',
            trigger=pgtrigger.compiler.Trigger(name='suites_count_decrement_statistics_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NOT OLD."is_deleted")', func='\n            UPDATE core_projectstatistics \n            SET suites_count = suites_count - 1 \n            WHERE project_id = OLD.project_id;\n            RETURN OLD;\n            ', hash='e3fc39a708833e8e328c90771b566be3d6f1e2a4', operation='DELETE', pgid='pgtrigger_suites_count_decrement_statistics_on_delete_c8363', table='tests_description_testsuite', when='BEFORE')),
        ),
    ]
