# Generated by Django 4.2.13 on 2024-12-03 15:19
from copy import deepcopy

from django.db import migrations
from django.db.models import OuterRef
from django.utils import timezone


def resolve_is_archive(apps, schema_editor):
    actual_model = apps.get_model('tests_description', 'TestCase')
    history_model = apps.get_model('tests_description', 'HistoricalTestCase')

    history_ids = actual_model.objects.filter(is_archive=True).annotate(
        latest_history=history_model.objects.filter(
            id=OuterRef('id')
        ).order_by('-history_date').values('pk')[:1]
    ).values_list('latest_history', flat=True)
    items = []
    for elem in history_model.objects.filter(pk__in=history_ids):
        new_elem = deepcopy(elem)
        new_elem.history_id = None
        new_elem.history_date += timezone.timedelta(seconds=1)  # delta for ordering
        new_elem.history_type = '~'
        new_elem.is_archive = True
        items.append(new_elem)
    history_model.objects.bulk_create(items)


class Migration(migrations.Migration):
    dependencies = [
        ('tests_description', '0022_remove_testcase_cases_count_decrement_statistics_on_update_and_more'),
    ]

    operations = [
        migrations.RunPython(resolve_is_archive, migrations.RunPython.noop),
    ]
