import {
  AlignLeftOutlined,
  AppstoreFilled,
  BarChartOutlined,
  CloseOutlined,
  DashOutlined,
  DownOutlined,
  FileDoneOutlined,
  FilterFilled,
  FolderOutlined,
  FullscreenOutlined,
  HolderOutlined,
  InboxOutlined,
  InfoCircleFilled,
  LeftOutlined,
  LoginOutlined,
  SaveOutlined,
  StarFilled,
  StarOutlined,
  SyncOutlined,
  TableOutlined,
  UngroupOutlined,
  UpOutlined,
  UserOutlined,
  UsergroupAddOutlined,
} from "@ant-design/icons"

import { IconsPackType } from "./types"

const AntIcons: IconsPackType = {
  ArchiveIcon: InboxOutlined,
  ArrowIcon: DownOutlined,
  BackIcon: LeftOutlined,
  BookmarkFillIcon: StarFilled,
  BookmarkIcon: StarOutlined,
  CloseIcon: CloseOutlined,
  CollapseIcon: UpOutlined,
  ColumnViewIcon: AppstoreFilled,
  ContextMenuIcon: DashOutlined,
  DashboardIcon: BarChartOutlined,
  DotsIcon: HolderOutlined,
  ExpandIcon: FullscreenOutlined,
  FilterIcon: FilterFilled,
  FilterPlusIcon: UngroupOutlined,
  InfoIcon: InfoCircleFilled,
  LogoutIcon: LoginOutlined,
  ResetIcon: SyncOutlined,
  SaveIcon: SaveOutlined,
  SorterIcon: AlignLeftOutlined,
  TableIcon: TableOutlined,
  TestPlansIcon: FileDoneOutlined,
  TestSuitesIcon: FolderOutlined,
  UserGroupsIcon: UsergroupAddOutlined,
  UserIcon: UserOutlined,
}

export { AntIcons }
