# Generated by Django 4.2.13 on 2025-04-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_customattribute_content_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='action_code',
            field=models.IntegerField(choices=[(0, 'Test assigned'), (1, 'Test unassigned'), (2, 'Test case modified'), (3, 'Test plan modified'), (4, 'Test bulk update')], primary_key=True, serialize=False),
        ),
    ]
